version: '3'
services:
  conformalpd:
    build:
      dockerfile: Dockerfile
      context: ..
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspaces:cached
      #- type: bind
      #  source: $HOME/rosetta
      #  target: /rosetta
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

